### ISSUE TITLE
a way of displaying fungible tokens from multiple minting policies to be commonly fungible in wallets

### ISSUE THREAD

**Issue by aleeusgr** [input-output-hk/Stablecoin-working-group#14]
For our product, there is a security requirement to rotate signing keys on a regular basis.
The side effect of this is that policy ID and token name will be different for each of the security cycles.
Essentially, the product will have to create multiple identical tokens, which will degrade user experience.

One way to solve it would be to implement a CIP for wallet apps to hide this information from end user: have some way to identify that a set of tokens belong to one family and display them as one token.

What are other possible approaches for solving this problem?

**Comment by MIxAxIM** [comment]
We can do that by something I call **Chain-of-Token** or **Proof-of-Token-Name** with current cardano parameter and protocol setting.

Chain-of-Token or **PoTN** means, as name suggest, we link tokens together by their token names, which previous minted token name string is future currency symbol string.
Right now we have limitation for length of token name which is 32 characters (64 in Hex), so we can not put whole currency symbol string (normally they are 56 characters / 112 in hex) into one token name but since a stable coin project design has 2 tokens (1st is the stable coin and another is the reserve coin), we can divide the future currency symbol into 2 and assign the token names with them. 

By doing **Chain-of-Token/PoTN** design pattern we can even have locked policy approach too, which user can be sure that a certain generation of stable coin is safe and secure. Same as what any government does with minting different generation of a currency, which old generation approves future generation.
